---

services:
    loader:
        restart: always
        image: rushiai/auto-reloader:v2.0.8
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
            - ./work:/work
            - ./keys:/root/.ssh

        ports:
            - 9870:9870

        working_dir: /work

        # uncomment this to run the check-push.sh script instead of web hook
        #command: /scripts/check-push.sh

        # uncomment this to run the git-supervisor
        #command: /git-supervisor watch --interval 120

        environment:
            - TZ=Asia/Shanghai
            - FORCE_COLOR=1
            - LOGLEVEL=2
               # default LOGLEVEL 2 means verbose
            - GITHUB_WEBHOOK_SECRET=1234567890
               # GITHUB_WEBHOOK_SECRET is required to run gh-webhook
            #- TIMEOUT=120
               # default timeout of possible pending cmd is 120s
            #- SLEEP_TIME=360
               # default sleep time is 360s
